sudo: required
services:
  - docker

before_install:
  - docker build -t kiiotory/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kiiotory/react-test npm run test -- --coverage

after_success:
  - docker build -t kiiotory/multi-client ./client
  - docker build -t kiiotory/multi-nginx ./nginx
  - docker build -t kiiotory/multi-server ./server
  - docker build -t kiiotory/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  # Take those images and push them to docker hub
  - docker push  kiiotory/multi-client
  - docker push  kiiotory/multi-nginx
  - docker push  kiiotory/multi-server
  - docker push  kiiotory/multi-worker
deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-651563370919
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY